name: hospital-front

services:
  frontend:
    build:
      context: .
    container_name: hospital-front
    restart: unless-stopped
    expose:
      - "8082"
    environment:
      VUE_APP_BASE_API: /hospital
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy